############ Experimental Settings #########
mode: train_diff   # order: train_diff, generate_diff, train_refine, test
seed: 1
num_seeds: 1
# device
gpu_index: 0
# dataset
dataset: h36m
data_dir: data/h3.6m/dataset
obs_frames: 25
pred_frames: 100
nk: 50    # the number of generated sequences
use_vel: False
normalize_data: False
# model
model_name: MotionDiff

############ DiffMotion Config #############
batch_size: 64
# optimizer
lr: 0.0005
num_diff_epoch_fix: 100
num_diff_epoch: 1000
# Train
save_model_interval: 50
iter_start_diff: 0
num_diff_data_sample: 4000
max_norm: False           # whether gradient clipping
num_generate_diff_data_sample: 5000
generate_diff_batch_size: 1
# DDPM Parameters
num_steps: 100     # the number of denoise procedure
beta_1: 1.0e-4
beta_T: 5.0e-2
flexibility: 0.0
ret_traj: False
pose_embed_dim: 32
drop_path_rate: 0.1
drop_rate_poseformer: 0.0
encoder_rnn: False
rnn_type: gru
rnn_output_dim: 512
tf_layer: 3

############ Refinement Config #############
refine_batch_size: 16
# optimizer
refine_lr: 5.0e-4
gcn_lr_decay: 2
gcn_lr_gamma: 0.96
# Train
iter_start_refine: 0
num_refine_epoch: 100
gcn_max_norm: True
# Refine Parameters
dct_n: 80
d_scale: 100000.0
gcn_linear_size: 256
gcn_dropout: 0.5
gcn_layers: 12
lambda_j: 1.0
lambda_recon: 200.0
gamma: 0.01

# Testing Parameters:
eval_at_diff: 1000
eval_at_refine: 100
multimodal_threshold: 0.5
mode_test: vis   # stats or vis






